import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service",
    description: "Terms of Service for OtherCalculators. Understand the rules for using our tools.",
};

export default function TermsOfService() {
    return (
        <main className="min-h-screen bg-slate-50 py-16 md:py-24">
            <div className="container mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
                <article className="rounded-2xl border border-slate-900/10 bg-white p-6 md:p-10 shadow-sm transition-all duration-300 hover:shadow-md">
                    <header className="mb-10 text-center">
                        <h1 className="text-4xl font-bold tracking-tight text-slate-900 sm:text-5xl mb-4">
                            Terms of Service
                        </h1>
                        <p className="text-slate-500 text-sm">Last Updated: February 8, 2026</p>
                    </header>

                    <div className="prose prose-slate max-w-none space-y-8 text-slate-700 leading-relaxed">
                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">1. Acceptance of Terms</h2>
                            <p>
                                By accessing and using <strong>OtherCalculators</strong> ("the Website"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please refrain from using our services.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">2. Use of Calculators</h2>
                            <p>
                                Our tools are provided for informational and educational purposes only. You agree to use these tools responsibly and for personal, non-commercial use unless otherwise specified.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">3. Accuracy of Results</h2>
                            <div className="bg-amber-50 border-l-4 border-amber-400 p-4 rounded-r-lg">
                                <p className="font-semibold text-amber-900">Disclaimer of Warranties</p>
                                <p className="text-amber-800 text-sm mt-1">
                                    While we strive for accuracy, calculation results are estimates and should not be used as the sole basis for professional, engineering, financial, or medical decisions.
                                </p>
                            </div>
                            <p className="mt-4">
                                OtherCalculators does not guarantee the accuracy, completeness, or reliability of any results generated by our tools.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">4. Limitation of Liability</h2>
                            <p>
                                In no event shall OtherCalculators or its developers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the tools on the Website.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">5. Intellectual Property</h2>
                            <p>
                                All content, formulas, and code on this site are the property of OtherCalculators and are protected by applicable copyright and trademark laws.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">6. Changes to Terms</h2>
                            <p>
                                We reserve the right to modify these Terms of Service at any time. Your continued use of the Website after any changes indicates your acceptance of the new terms.
                            </p>
                        </section>

                        <section>
                            <h2 className="text-2xl font-bold text-slate-900 mb-4 border-b border-slate-100 pb-2">7. Governing Law</h2>
                            <p>
                                These terms shall be governed by and construed in accordance with the laws of the jurisdiction in which the service operates, without regard to its conflict of law provisions.
                            </p>
                        </section>
                    </div>
                </article>
            </div>
        </main>
    );
}
